name: Dispatch

on:
  repository_dispatch:
    types: 
      - dispatch_foo
      - dispatch_bar
      - 'manifest-change::Waypoint'
      - 'manifest-change::Terraform'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ github.event.client_payload.list }}
    steps:
      - name: 'Checkout ${{ github.event.client_payload.foo }}'
        uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.foo }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - run: echo baz
        if: github.event.action == 'baz'
  my_matrix:
    runs-on: ubuntu-latest
    needs: say_hello
    strategy:
      matrix: ${{ fromJson(needs.say_hello.outputs.list) }}
    steps:
      - run: echo ${{ matrix.display }}